### ISSUE TITLE
time.h included but not used

### ISSUE THREAD

**Issue by TTAK** [Seeed-Studio/Grove_Barometer_HP20x#1]
I have difficulties to compile KalmanFilter, the error is file time.h not found.

I checked the file KalmanFilter.cpp and I think despite you included it, you are not using time.h. 
Maybe you should remove the line ?

Maybe I am wrong but maybe have a look at it just to be sure.

regards,
TTAK

**Comment by nqray** [comment]
I fully agree with TTAK. I was unable to compile my sketches the last time I updated my arduino IDE. Same conclusion: one include line to remove.

**Comment by KillingJacky** [comment]
Thanks guys, it's fixed.
