### ISSUE TITLE
Cannot compile - missing TwoWire library

### ISSUE THREAD

**Issue by ElectronicaXAB3** [Seeed-Studio/Grove_Barometer_HP20x#3]
I loaded your example into Arduino 1.8.1 and I cannot compile it, because of missing TwoWire library:

```
D:\Program Files\arduino-1.8.1\libraries\HP20x_dev\HP20x_dev.cpp: In constructor 'HP20x_dev::HP20x_dev()':

D:\Program Files\arduino-1.8.1\libraries\HP20x_dev\HP20x_dev.cpp:33:22: error: no matching function for call to 'TwoWire::TwoWire()'

 HP20x_dev::HP20x_dev()
```

**Comment by KillingJacky** [comment]
No problem here, Arduino version 1.8.3, TwoWire is a builtin library of Arduino IDE, please reinstall your Arduino IDE.

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
